### ISSUE TITLE
Diamond Jubilee Series

### ISSUE THREAD

**Issue by sornig** [richyliu/greggdict#15]
Hey, are you planning to add the Diamond Jubilee Series dictionary as well? I don't know how much it differs from other variants like Simplified, so maybe its unnecessary... I have the PDF in my calibre library already (dl from internet archive) and its (kind of) searchable, but its definitely not a pleasurable experience because of all the random characters in between words.

btw thanks for this great tool! Its incredibly helpful for quickly looking up words on the go and comparing strokes
_(on that note, a 'compare' button that allows searching for a second word and display them side-by-side would also be a great addition – should i put that in a seperate issue?)_

**Comment by richyliu** [comment]
I'm not actively adding new features anymore, but feel free to make a pull request and I can merge it.
